import Image from "next/image"
import { Button } from "./ui/button";

export default function Hero() {
  return (
    <div className="max-w-[512px] flex flex-col items-center gap-4 py-20">
      <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl text-blue-600 text-center">
        100 design briefs generated by ChatGPT.
      </h1>
      <p className="leading-7 [&:not(:first-child)]:mt-6 text-center text-gray-500">
        Work on your design skills with 100 project ideas to build over the
        weekend. Don&apos;t forget to have fun!
      </p>
      <Button>Give me a brief</Button>
    </div>
  );
}
