'use client'

import { Button } from "./ui/button";
import Link from "next/link";
import { motion } from "framer-motion";


export default function Hero() {

  return (
    <div className="max-w-[512px] flex flex-col items-center gap-4 py-20">
      <motion.h1
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, type: "spring", damping: 20, delay: 0.4 }}
        className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl text-blue-600 text-center"
      >
        100 design briefs generated by ChatGPT.
      </motion.h1>
      <motion.p
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, type: "spring", damping: 20, delay: 0.6 }}
        className="leading-7 [&:not(:first-child)]:mt-6 text-center text-gray-500"
      >
        Work on your design skills with 100 project ideas to build over the
        weekend. Don&apos;t forget to have fun!
      </motion.p>
      <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, type: "spring", damping: 20, delay: 0.8 }}
      >
        <Link href={"/brief"}>
          <Button>Give me a brief</Button>
        </Link>
      </motion.div>
    </div>
  );
}
