"use client";

// Import necessary components and data
import Brief from "@/components/Brief";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Button } from "@/components/ui/button";
import projects from "@/public/data/projects.json";
import { motion } from "framer-motion";
import Link from "next/link";

import { useState, useEffect } from "react";

export default function Page() {
  const [selectedProjectIndex, setSelectedProjectIndex] = useState(0);

  useEffect(() => {
    // Function to select a random index
    const randomIndex = Math.floor(Math.random() * projects.projects.length);
    setSelectedProjectIndex(randomIndex);
  }, []); // Run this effect only once when the component mounts

  const selectedProject = projects.projects[selectedProjectIndex];
  return (
    <div className="flex flex-col sm:gap-24 items-center justify-center px-4">
      <Header />

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 2.0, delay: 0.5 }}
        className="max-w-[528px] flex flex-col gap-6 mb-4"
      >
        <h2 className="scroll-m-20 text-xl font-semibold tracking-tight">
          100 design briefs generated by ChatGPT
        </h2>
        <Brief
          projectTitle={selectedProject.title}
          projectIndustry={selectedProject.industry}
          projectBrief={selectedProject.description}
        />
        <div className="flex gap-4 w-full justify-between">
          <Button
            onClick={() => {
              const randomIndex = Math.floor(
                Math.random() * projects.projects.length
              );
              setSelectedProjectIndex(randomIndex);
            }}
            variant="outline"
          >
            Give me another one
          </Button>
          {/* <Link href={""}>
            <Button>Add to board</Button>
          </Link> */}
        </div>
      </motion.div>
      {/* Map each project to a Brief component */}

      <div className="fixed bottom-0 w-full">
        <Footer />
      </div>
    </div>
  );
}
